name: vpb_flutter_boilerplate
description: Flutter project boilerplate.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter         

dev_dependencies:
  flutter_test:
    sdk: flutter
  local_auth: ^1.1.6
  flutter_bloc: ^7.0.1
  dio: ^4.0.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  firebase_crashlytics: ^2.0.5
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.2
  # flutter_local_notifications: ^6.0.0 // if you want to implement display noti while app in foreground
  equatable: ^2.0.3
  cached_network_image: ^3.0.0
  image_picker: ^0.8.0+1
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  http: ^0.13.3
  # candlesticks: ^0.5.0
  k_chart: ^0.3.1
  pull_to_refresh: ^2.0.0
  form_field_validator: ^1.1.0
  # flutter_secure_storage is secured storage for both iOS (keychain) and android (AES encryption) 
  flutter_secure_storage: ^4.2.0
  # combination all connectivity_plus & data_connection_checker to handle internet connection changes
  connectivity_plus: ^1.0.4
  data_connection_checker: ^0.3.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
    - assets/themes/
